;[Command]
;name = "autocombo"
;command = D,D,D,D,D,D
;time = 40

;-| CPU -----------------------------------------------------------
[Command]
name = "cpu_1"
command = U, U, U, U, U
time = 1

[Command]
name = "cpu_2"
command = D, D, D, D, D
time = 1

[Command]
name = "cpu_3"
command = x, x, x, x, x
time = 1

[Command]
name = "cpu_4"
command = y, y, y, y, y
time = 1

[Command]
name = "cpu_5"
command = z, z, z, z, z
time = 1

[Command]
name = "cpu_6"
command = a, a, a, a, a
time = 1

[Command]
name = "cpu_7"
command = b, b, b, b, b
time = 1

[Command]
name = "cpu_8"
command = c, c, c, c, c
time = 1

[Command]
name = "cpu_9"
command = s, s, s, s, s
time = 1

[Command]
name = "cpu_10"
command = U, D, U, D, U
time = 1

[Command]
name = "cpu_11"
command = D, U, D, U, D
time = 1

[Command]
name = "cpu_12"
command = U, U, U, U, U
time = 1

[Command]
name = "cpu_13"
command = D, D, D, D, D
time = 1

[Command]
name = "cpu_14"
command = x, x, x, x, x
time = 1

[Command]
name = "cpu_15"
command = y, y, y, y, y
time = 1

[Command]
name = "cpu_16"
command = z, z, z, z, z
time = 1

[Command]
name = "cpu_17"
command = a, a, a, a, a
time = 1

[Command]
name = "cpu_18"
command = b, b, b, b, b
time = 1

[Command]
name = "cpu_19"
command = c, c, c, c, c
time = 1

[Command]
name = "cpu_20"
command = s, s, s, s, s
time = 1

[Command]
name = "cpu_21"
command = U, D, U, D, U
time = 1

[Command]
name = "cpu_22"
command = D, U, D, U, D
time = 1

[Command]
name = "cpu_23"
command = U, U, U, U, U
time = 1

[Command]
name = "cpu_24"
command = D, D, D, D, D
time = 1

[Command]
name = "cpu_25"
command = x, x, x, x, x
time = 1

[Command]
name = "cpu_26"
command = y, y, y, y, y
time = 1

[Command]
name = "cpu_27"
command = z, z, z, z, z
time = 1

[Command]
name = "cpu_28"
command = a, a, a, a, a
time = 1

[Command]
name = "cpu_29"
command = b, b, b, b, b
time = 1

[Command]
name = "cpu_30"
command = c, c, c, c, c
time = 1

[Command]
name = "cpu_31"
command = s, s, s, s, s
time = 1

;-| finishmoves |--------------------------
;[Command]
;name = "SAPO"
;command = ~D, F, B, a
;time = 40

;[Command]
;name = "BAT"
;command = ~D, B, F, a
;time = 40

;[Command]
;name = "TITS"
;command = ~B, F, B, F, x
;time = 40

;[Command]
;name = "TITS1"
;command = ~F, D, B, b
;time = 40

;[Command]
;name = "BATS"
;command = ~B, D, B, y
;time = 40

;[Command]
;name = "HEAD"
;command = ~F, D, F, z
;time = 40

;[Command]
;name = "ELEK"
;command = ~B, D, F, c
;time = 40

;-| Super Motions |--------------------------------------------------------
[Command]
name = "DF+X"
command = ~D, F, x
time = 40

[Command]
name = "DF+Y"
command = ~D, F, y
time = 40

[Command]
name = "DF+Z"
command = ~D, F, z
time = 40

[Command]
name = "BDF+X"
command = ~B, D, F, x
time = 20

[Command]
name = "BDF+Y"
command = ~B, D, F, y
time = 20

[Command]
name = "BDF+Z"
command = ~B, D, F, z
time = 20

[Command]
name = "BDF+Y"
command = ~B, D, F, y
time = 20

[Command]
name = "BDF+Z"
command = ~B, D, F, z
time = 20

[Command]
name = "FDB+X"
command = ~F, D, B, a
time = 20

[Command]
name = "FDB+Y"
command = ~F, D, B, b
time = 20

[Command]
name = "FDB+Z"
command = ~F, D, B, c
time = 20

[Command]
name = "FDB+C"
command = ~F, D, B, z
time = 20

[Command]
name = "TIGER-Y1"
command = ~F,y
time = 30

[Command]
name = "TIGER-X"
command = ~10$B, F,x
time = 30

[Command]
name = "TIGER-Y"
command = ~10$B, F,y
time = 30

[Command]
name = "TIGER-Z"
command = ~10$B, F,z
time = 30

[Command]
name = "TIGER-AIR"
command = ~10$F, B,y
time = 30


[Command]
name = "TRLK"
command = ~10$B, F+a
time = 30

[Command]
name = "TRLK1"
command = ~10$B, F, a
time = 30

[Command]
name = "TRMK"
command = ~10$B, F+b
time = 30

[Command]
name = "TRMK1"
command = ~10$B, F, b
time = 30

[Command]
name = "TRFK"
command = ~10$B, F+c
time = 30

[Command]
name = "TRFK1"
command = ~10$B, F, c
time = 30

;-| Special Motions |------------------------------------------------------
[Command]
name = "longjump"
command = ~D, $U
time = 10

;-| 2/3 Button Combination |-----------------------------------------------
[Command]
name = "recovery"
command = x+y
time = 1

;-| Dir + Button |---------------------------------------------------------

[Command]
name = "hold_BACK,b"
command = /B,b
time = 30

[Command]
name = "hold_BACK,b"
command = ~10$B,b
time = 30

[Command]
name = "hold_BACK,c"
command = /B,c
time = 30

name = "hold_BACK,c"
command = /B+c
time = 10

[Command]
name = "hold_BACK,c"
command = ~10$B,c
time = 30

[Command]
name = "hold_BACK,c"
command = ~10$B+c
time = 30

[Command]
name = "hold_BACK,z"
command = /B,z
time = 30

name = "hold_BACK,z"
command = /B+z
time = 30

[Command]
name = "hold_BACK,z"
command = ~10$B,z
time = 30

[Command]
name = "hold_BACK,z"
command = ~10$B+z
time = 30


;-| Single Button |---------------------------------------------------------

[Command]
name = "U"
command = U
time = 1

[Command]
name = "D"
command = D
time = 1

[Command]
name = "B"
command = B
time = 1

[Command]
name = "F"
command = F
time = 1

[Command]
name = "a"
command = a
time = 1

[Command]
name = "hold_a"
command = /a
time = 1

[Command]
name = "b"
command = b
time = 1

[Command]
name = "hold_b"
command = /b
time = 1

[Command]
name = "c"
command = c
time = 1

[Command]
name = "x"
command = x
time = 1

[Command]
name = "hold_x"
command = /x
time = 1

[Command]
name = "y"
command = y
time = 1

[Command]
name = "hold_y"
command = /y
time = 1

[Command]
name = "z"
command = z
time = 1

[Command]
name = "s"
command = s
time = 1

;-| Hold Dir |--------------------------------------------------------------

[Command]
name = "holdfwd"
command = /$F
time = 1

[Command]
name = "holdback"
command = /$B
time = 1

[Command]
name = "holdup"
command = /$U
time = 1

[Command]
name = "holddown"
command = /$D
time = 1

;---doubletab--------------
[Command]
name = "BB"     ;Required (do not remove)
command = B, B
time = 10

[Command]
name = "FF"     ;Required (do not remove)
command = F, F
time = 10

;-|Commands|------------------------------------------------------------------------------
[Statedef -1]
;***************************
;**      FINISHMOVES      **
;***************************

        ;ELEK
;	[State -1]
;	type = ChangeState
;	triggerall = stateno != 21000
;      triggerall = stateno != 91011
;      triggerall = stateno != 91000
;      triggerall = stateno != 91002
;      triggerall = stateno != 91004
;      triggerall = stateno != 91006
;        triggerall = stateno != 21009
;        triggerall = var(10)=0
;        triggerall = var(58)>=1
;	trigger1 = ctrl = 1
;        trigger1 = p2stateno = 003
;	trigger1 = p2life <100
;	trigger1 = command = "ELEK" && statetype = S
;	value = 22025

;        ;HEAD
;	[State -1]
;	type = ChangeState
;	triggerall = stateno != 21000
 ;     triggerall = stateno != 91011
;      triggerall = stateno != 91000
;      triggerall = stateno != 91002
;      triggerall = stateno != 91004
;      triggerall = stateno != 91006
;        triggerall = stateno != 21009
;        triggerall = var(10)=0
;        triggerall = var(58)>=1
;	triggerall = ctrl = 1
;        trigger1 = p2name = "B.ORCHID BY AHRIMANES"
;        trigger2 = p2name = "sub-zero by binho"
;        trigger3 = p2name = "Kelly Blender(Elektra) by AHRIMANES"
;	triggerall = p2stateno = 003
;	triggerall = p2life <100
;	triggerall = command = "HEAD" && statetype = S
;	value = 22020

;        ;BATS
;	[State -1]
;	type = ChangeState
;	triggerall = stateno != 21000
;      triggerall = stateno != 91011
;      triggerall = stateno != 91000
;      triggerall = stateno != 91002
;      triggerall = stateno != 91004
;      triggerall = stateno != 91006
;       triggerall = stateno != 21009
;        triggerall = var(10)=0
;        triggerall = var(58)>=1
;	trigger1 = ctrl = 1
;	trigger1 = p2stateno = 003
;	trigger1 = p2life <100
;	trigger1 = command = "BATS" && statetype = S
;	value = 22013

;	;tits
;	[State -1]
;	type = ChangeState
;	triggerall = stateno != 21000
;      triggerall = stateno != 91011
;      triggerall = stateno != 91000
;      triggerall = stateno != 91002
;      triggerall = stateno != 91004
;      triggerall = stateno != 91006
;        triggerall = stateno != 21009
;        triggerall = var(10)=0
;        triggerall = var(58)>=1
;	trigger1 = ctrl = 1
;	trigger1 = p2stateno = 003
;	trigger1 = p2life <100
;	trigger1 = command = "TITS" && statetype = S
;	value = 22010

	;tits
;	[State -1]
;	type = ChangeState
;	triggerall = stateno != 21000
;      triggerall = stateno != 91011
;      triggerall = stateno != 91000
;      triggerall = stateno != 91002
;      triggerall = stateno != 91004
;      triggerall = stateno != 91006
;        triggerall = stateno != 21009
;        triggerall = var(10)=0
;        triggerall = var(58)>=1
;	trigger1 = ctrl = 1
;	trigger1 = p2stateno = 003
;	trigger1 = p2life <100
;	trigger1 = command = "TITS" && statetype = S && p2statetype = S
;	trigger2 = ctrl = 0
;	trigger2 = command = "TITS1" && statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
;	trigger2 = p2life < 100
;	trigger2 = var(35) >1
;	value = 22010


        ;DANCE
;	[State -1]
;	type = ChangeState
;	trigger1 = P2name = "B.ORCHID BY AHRIMANES"
;	trigger2 = P2name = "cvssakura"
;	triggerall = stateno != 21000
 ;       triggerall = stateno != 21009
;        triggerall = var(10)=0
 ;       triggerall = var(58)>=1
;	triggerall = ctrl = 1
;	triggerall = p2stateno = 003
;	triggerall = p2life <100
;	triggerall = command = "FDB+Z" && statetype = S
;	value = 22001

	;SAPO
	;[State -1]
	;type = ChangeState
	;triggerall = stateno != 21000
      ;triggerall = stateno != 91011
      ;triggerall = stateno != 91000
      ;triggerall = stateno != 91002
      ;triggerall = stateno != 91004
      ;triggerall = stateno != 91006
     ; triggerall = stateno != 21009
     ; triggerall = var(10)=0
     ; triggerall = var(58)>=1
;	trigger1 = ctrl = 1
;	trigger1 = p2stateno = 003
;	trigger1 = p2life <100
;	trigger1 = command = "SAPO" && statetype = S && P2bodydist X <= 70 && p2statetype = S || command = "BAT" && statetype = S && P2bodydist X <= 70 && p2statetype = S
;	trigger2 = ctrl = 0
;	trigger2 = command = "SAPO" && statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S ||command = "BAT" && statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
;	trigger2 = p2life < 100
;	trigger2 = var(35) >1
;	value = 21000

	;Ultra
	[State -1]
	type = ChangeState
	triggerall = stateno != 21000
      triggerall = stateno != 91011
      triggerall = stateno != 91000
      triggerall = stateno != 91002
      triggerall = stateno != 91004
      triggerall = stateno != 91006
      triggerall = stateno != 21009
      triggerall = var(10)= 0
      triggerall = command = "TIGER-Y"
      triggerall = command != "FDB+Y"
      triggerall = ctrl = 0
	triggerall = p2life < 100
	triggerall = var(35) >1
	trigger1 = time > 59
	trigger1 = stateno = 90003
	trigger2 = time > 44
	trigger2 = stateno = 90000
	trigger3 = time > 51
	trigger3 = stateno = 90005
	trigger4 = time > 40
	trigger4 = stateno = 1300
	trigger5 = time >53
	trigger5 = Var(35) >6
	trigger5 = stateno = 1220
	trigger6 = time > 51
	trigger6 = stateno = 90006
	trigger7 = time >20
	trigger7 = var(35)
	trigger7 = stateno = 1110
	trigger8 = var(35)>1
	trigger8 = stateno = 247
	trigger9 = var(35)>1
	trigger9 = stateno = 90008
	value = 21006



;**************
;*    trow    *
;**************
[State -1, Kung Fu Throw]
type = ChangeState
value = 800
triggerall = command = "c"
triggerall = statetype = S
triggerall = ctrl
triggerall = stateno != 100
trigger1 = command = "holdfwd"
trigger1 = p2bodydist X < 3
trigger1 = (p2statetype = S) || (p2statetype = C)
trigger1 = p2movetype != H


;***************************
;**         SUPER         **
;***************************

;bola hacia adelante com puño debil "BDF+X"
[State -1]
type = ChangeState
triggerall = command = "BDF+X" && statetype = S
trigger1 = ctrl
value = 1000

;bola hacia adelante com cualquierpuño, para speed combos
[State -1]
type = ChangeState
value = 1004
triggerall = stateno = [200,265]; || stateno = [270,370]
triggerall = movecontact 
trigger1 = command = "DF+X"
trigger2 = command = "DF+Y"
trigger3 = command = "DF+Z"


;bola hacia adelante com puño medio "BDF+Y"
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "BDF+Y" && statetype = S
value = 1001

;bola hacia adelante com puño fuerte "BDF+Z"
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "BDF+Z" && statetype = S
value = 1002

;bola hacia atras com patada "FDB+C"
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "FDB+C" && statetype = A
value = 91010

;bola hacia atras com puño debil "FDB+X"
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "FDB+X" && statetype = S
value = 1100

;bola hacia atras com puño debil "FDB+Y"
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "FDB+Y" && statetype = S
value = 1110

;bola hacia atras com puño fuerte "FDB+Z"
[State -1]
type = ChangeState
triggerall = command = "FDB+Z" 
trigger1 = statetype = S
trigger1 = ctrl
trigger2 = stateno = [200,265]
trigger2 = movecontact 
trigger3 = stateno = [270,370]
trigger3 = movecontact 
value = 1150

; holdback Standing hard kick
[State -1]
type = ChangeState
value = 267
trigger1 = command = "c" && statetype = S && command = "holdback" && ctrl
trigger2 = command = "c" && statetype = S && command = "holdback"
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260) || (stateno = [265,266])
trigger2 = movecontact

; COMBOBREAKER
[State -1]
type = ChangeState
triggerall = ctrl = 0
triggerall = movetype = H
triggerall = life > 100
triggerall = Var(32)>2
trigger1 = command = "TRLK"&& statetype = S
trigger2 = command = "TRLK1"&& statetype = S
trigger3 = command = "TRMK"&& statetype = S
trigger4 = command = "TRMK1"&& statetype = S
trigger5 = command = "TRFK"&& statetype = S
trigger6 = command = "TRFK1"&& statetype = S
trigger7 = command = "TRLK"&& statetype = C
trigger8 = command = "TRLK1"&& statetype =C
trigger9 = command = "TRMK"&& statetype = C
trigger10 = command = "TRMK1"&& statetype = C
trigger11 = command = "TRFK"&& statetype = C
trigger12 = command = "TRFK1"&& statetype = C
value = 1230

; taunt
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "s"&& statetype = S
value = 195

; TIGER-X
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "TIGER-X"&& statetype = S
value = 1400

; TIGER-Y
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "TIGER-Y"&& statetype = S
trigger2 = command = "TIGER-Y1"&& stateno = 100
value = 1401

; TIGER-Z
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "TIGER-Z"&& statetype = S
value = 1402


; CHOPER LOW KICK
[State -1]
type = ChangeState
triggerall = ctrl = 1
trigger1 = command = "TRLK"&& statetype = S
trigger2 = command = "TRLK1"&& statetype = S
value = 1200


; CHOPER MED KICK
[State -1]
type = ChangeState
value = 1210
triggerall = ctrl = 1
trigger1 = command = "TRMK"&& statetype = S
trigger2 = command = "TRMK1"&& statetype = S


; CHOPER HARD KICK
[State -1]
type = ChangeState
value = 1220
triggerall = ctrl = 1
trigger1 = command = "TRFK"&& statetype = S
trigger2 = command = "TRFK1"&& statetype = S


;***************************
;**    op air to st       **
;***************************
[state -1]
type = changestate
value = 90005
triggerall = command = "b"
triggerall = statetype = S
trigger1 = stateno!=90005
trigger1 = var(12)

[state -1]
type = changestate
value = 90008
triggerall = command = "y"
triggerall = statetype = S
trigger1 = stateno!=90008
trigger1 = var(12)

[state -1]
type = varset
trigger1 = time = 15
var(12)=0

;***************************
;**        NORMALES       **
;***************************
; TIGER-R
;[State -1]
;type = ChangeState
;triggerall = ctrl = 0
;triggerall = movehit
;triggerall = command = "TIGER-AIR"&& statetype = A
;trigger1 = stateno = 600
;trigger2 = stateno = 610
;trigger3 = stateno = 620
;trigger4 = stateno = 630
;trigger5 = stateno = 640
;trigger6 = stateno = 650
;value = 1403

;jum low punch
[State -1]
type = ChangeState
value = 600
triggerall = command = "x"
triggerall = statetype = A
trigger1 = ctrl

;jum med punch
[State -1]
type = ChangeState
value = 610
triggerall = command = "y"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600
trigger2 = movecontact
trigger3 = stateno = 630
trigger3 = movecontact

;jum hard punch
[State -1]
type = ChangeState
value = 620
triggerall = command = "z"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = [600,610]
trigger2 = movecontact
trigger3 = stateno = [630,640]
trigger3 = movecontact

;jum low kick
[State -1]
type = ChangeState
value = 630
triggerall = command = "a"
triggerall = statetype = A
trigger1 = ctrl

;jum med kick
[State -1]
type = ChangeState
value = 640
triggerall = command = "b"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = 600
trigger2 = movecontact
trigger3 = stateno = 630
trigger3 = movecontact

;jum hard kick
[State -1]
type = ChangeState
value = 650
triggerall = command = "c"
triggerall = statetype = A
trigger1 = ctrl
trigger2 = stateno = [600,610]
trigger2 = movecontact
trigger3 = stateno = [630,640]
trigger3 = movecontact

;hold back standing hard punch2
[State -1]
type = Changestate
value = 247
triggerall = command = "z"
triggerall = command = "holdback"
triggerall = command != "FDB+Z"
triggerall = command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260) || (stateno = 220) || (stateno = 205)
trigger2 = movecontact

;close standing hard punch
[State -1]
type = ChangeState
triggerall = command = "z" 
triggerall = command != "holddown"
trigger1 = statetype = S && P2bodydist X <= 20 && ctrl
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)
trigger2 = movecontact
value = 205

; Close Standing light punch 2
[State -1]
type = ChangeState
value = 244
triggerall = stateno = 245
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S && command != "holddown" && P2bodydist X <= 10 && movecontact && time >= 11

; Close Standing light punch
[State -1]
type = ChangeState
value = 245
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S && command != "holddown" && P2bodydist X <= 10 && ctrl
trigger2 = stateno = 244 && P2bodydist X <= 10 && movecontact && time >= 11

; Standing light punch 2
[State -1]
type = ChangeState
value = 250
triggerall = stateno = 240
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S && command != "holddown"
trigger1 = time >= 10 && movecontact

; Standing light punch
[State -1]
type = ChangeState
value = 240
triggerall = command = "x"
triggerall = command != "holddown"
trigger1 = statetype = S && command != "holddown" && ctrl
trigger2 = stateno = 250
trigger2 = time >= 11 && movecontact

;close standing med punch
[State -1]
type = ChangeState
triggerall = command = "y" 
triggerall = command != "holddown"
trigger1 = statetype = S && P2bodydist X <= 10 && ctrl
trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])
trigger2 = movecontact
value = 246

; Standing med punch
[State -1]
type = ChangeState
value = 200
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S && command != "holddown" && ctrl
trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])
trigger2 = movecontact

; Standing hard punch
[State -1]
type = ChangeState
value = 220
triggerall = command = "z" && command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)
trigger2 = movecontact

;close standing hard kick
[State -1]
type = ChangeState
value = 266
triggerall = command = "c" && P2bodydist X <= 15 
triggerall = command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)
trigger2 = movecontact

;close Standing med kick
[State -1]
type = ChangeState
value = 232
triggerall = command = "b" && P2bodydist X <= 15
triggerall = command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])
trigger2 = movecontact

;close Standing light kick
[State -1]
type = ChangeState
value = 231
triggerall = command = "a" && P2bodydist X <= 15
triggerall = command != "holddown"
trigger1 = ctrl && statetype = S

;standing hard kick
[State -1]
type = ChangeState
value = 265
triggerall = command = "c"  && command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)
trigger2 = movecontact

;Standing med kick
[State -1]
type = ChangeState
value = 260
trigger1 = var(9) = 0
triggerall = command = "b" && command != "holddown"
trigger1 = ctrl && statetype = S
trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])
trigger2 = movecontact

; Standing light kick
[State -1]
type = ChangeState
value = 230
triggerall = command = "a" && command != "holddown"
trigger1 = ctrl && statetype = S

;Crouching light punch
[State -1]
type = ChangeState
value = 300
triggerall = command = "x" 
trigger1 = ctrl && statetype = C
;trigger2 = StateType != A & MoveContact
;trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])

;Crouching med punch
[State -1]
type = ChangeState
value = 310
triggerall = command = "y" 
trigger1 = ctrl && statetype = C
trigger2 = (stateno = 300) || (stateno = 350)
trigger2 = movecontact
;trigger3 = StateType != A & MoveContact
;trigger3 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])

;Crouching hard punch
[State -1]
type = ChangeState
value = 320
triggerall = command = "z" && statetype = C
trigger1 = ctrl
trigger2 = (stateno = 300) || (stateno = 310) || (stateno = 350) || (stateno = 360)
trigger2 = movecontact
;trigger3 = StateType != A & MoveContact
;trigger3 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)

; crouching low kick
[State -1]
type = ChangeState
value = 350
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = Ctrl = 1
;trigger2 = StateType != A & MoveContact
;trigger2 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])

; crouching med kick
[State -1]
type = ChangeState
value = 360
triggerall = Command = "b"
triggerall = Command = "holddown"
trigger1 = StateType = C
trigger1 = Ctrl = 1
trigger2 = (stateno = 300) || (stateno = 350)
trigger2 = movecontact
;trigger3 = StateType != A & MoveContact
;trigger3 = (stateno = [240,245]) || (stateno = 250) || (stateno = [230,231])

; crouching hard kick
[State -1]
type = ChangeState
value = 370
triggerall = Command = "c"
triggerall = Command = "holddown"
trigger1 = StateType = C
trigger1 = Ctrl = 1
trigger2 = (stateno = 300) || (stateno = 310) || (stateno = 350) || (stateno = 360)
trigger2 = movecontact
;trigger3 = StateType != A & MoveContact
;trigger3 = (stateno = [240,246]) || (stateno = 250) || (stateno = 200) || (stateno = [230,232]) || (stateno = 260)

;---------------------------------------------------------------------------
;Run Back
[State -1, Run Back]
type = ChangeState
value = 105
triggerall = command = "BB" 
triggerall = statetype = S
trigger1 = ctrl
trigger2 = movetype = H

;---------------------------------------------------------------------------
;Run fw..
[State -1, Run fw]
type = ChangeState
value = 100
triggerall = command = "FF" 
triggerall = statetype = S
trigger1 = ctrl

; Taunt
;[State -1]
;type = ChangeState
;value = IfElse((Var(4) = 0),195,6195)
;trigger1 = command = "s" && statetype = S && ctrl
;trigger1 = stateno != 195 && stateno != 196 && stateno != 6195 && stateno != 6196



;************************
;**     Combo enders  **
;************************

;(fdbc)
;[state -1]
;type = changestate
;value = 91011
;triggerall = movehit
;triggerall = ctrl = 0
;triggerall = command = "FDB+C"||command = "FDB+C"
;trigger1 = time > 34
;trigger1 = stateno = 1403


;(bfa)
[state -1]
type = changestate
value = 91000
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "TRLK"||command = "TRLK1"
trigger1 = time > 59
trigger1 = stateno = 90003
trigger2 = time > 44
trigger2 = stateno = 90000
trigger3 = time > 51
trigger3 = stateno = 90005
trigger4 = time > 40
trigger4 = stateno = 1300
trigger5 = time >53
trigger5 = Var(35) >6
trigger5 = stateno = 1220
trigger6 = time > 51
trigger6 = stateno = 90006
trigger7 = time >20
trigger7 = var(35)
trigger7 = stateno = 1110
trigger8 = var(35)>1
trigger8 = stateno = 247
trigger9 = var(35)>1
trigger9 = stateno = 90008
trigger10 = time >22
trigger10 = stateno = 91008

;(bfb)
[state -1]
type = changestate
value = 91002
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "TRMK"||command = "TRMK1"
trigger1 = Var(35) >6
trigger1 = time >53
trigger1 = stateno = 1220
trigger2 = time > 40
trigger2 = stateno = 1300
trigger3 = time > 51
trigger3 = stateno = 90005
trigger4 = time > 59
trigger4 = stateno = 90003
trigger5 = time > 44
trigger5 = stateno = 90000
trigger6 = time > 51
trigger6 = stateno = 90006
trigger7 = time >20
trigger7 = var(35)
trigger7 = stateno = 1110
trigger8 = var(35)>1
trigger8 = stateno = 247
trigger9 = var(35)>1
trigger9 = stateno = 90008
trigger10 = time >22
trigger10 = stateno = 91008


;(bdfz)
[state -1]
type = changestate
value = 91004
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "BDF+Z"
trigger1 = Var(35) >6
trigger1 = time >53
trigger1 = stateno = 1220
trigger2 = time > 40
trigger2 = stateno = 1300
trigger3 = time > 51
trigger3 = stateno = 90005
trigger4 = time > 59
trigger4 = stateno = 90003
trigger5 = time > 44
trigger5 = stateno = 90000
trigger6 = time > 51
trigger6 = stateno = 90006
trigger7 = time >20
trigger7 = var(35)
trigger7 = stateno = 1110
trigger8 = var(35)>1
trigger8 = stateno = 247
trigger9 = var(35)>1
trigger9 = stateno = 90008
trigger10 = time >22
trigger10 = stateno = 91008

;(fdbz)
[state -1]
type = changestate
value = 91006
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "FDB+Z"
trigger1 = Var(35) >6
trigger1 = time >53
trigger1 = stateno = 1220
trigger2 = time > 40
trigger2 = stateno = 1300
trigger3 = time > 51
trigger3 = stateno = 90005
trigger4 = time > 59
trigger4 = stateno = 90003
trigger5 = time > 44
trigger5 = stateno = 90000
trigger6 = time > 51
trigger6 = stateno = 90006
trigger7 = time >20
trigger7 = var(35)
trigger7 = stateno = 1110
trigger8 = var(35)>1
trigger8 = stateno = 247
trigger9 = var(35)>1
trigger9 = stateno = 90008
trigger10 = time >22
trigger10 = stateno = 91008

;************************
;**     Combo openers  **
;************************

; TIGER-R
;[State -1]
;type = ChangeState
;triggerall = ctrl = 0
;triggerall = movehit
;triggerall = command = "TIGER-AIR"&& statetype = A
;trigger1 = stateno = 600
;trigger2 = stateno = 610
;trigger3 = stateno = 620
;trigger4 = stateno = 630
;trigger5 = stateno = 640
;trigger6 = stateno = 650
;value = 1403

[state -1]
type = changestate
value = 90000
triggerall = command = "x"
triggerall = movehit
triggerall = ctrl = 0
trigger1 = time >53
trigger1 = stateno = 1220
trigger2 = time >22
trigger2 = stateno = 91008

[state -1]
type = changestate
value = 90003
triggerall = command = "a"
triggerall = movehit
triggerall = ctrl = 0
trigger1 = time >42
trigger1 = stateno = 1210
trigger2 = time >22
trigger2 = stateno = 91008

[state -1]
type = changestate
value = 90005
triggerall = command = "b"
triggerall = movehit
triggerall = ctrl = 0
trigger1 = time >42
trigger1 = stateno = 1300
trigger2 = time >28
trigger2 = stateno = 1301
trigger3 = time >20
trigger3 = stateno = 1110
trigger4 = time >63
trigger4 = stateno = 1401
trigger5 = time >33
trigger5 = stateno = 1401
trigger5 = anim = 1404

[state -1]
type = changestate
value = 90005
triggerall = command = "c"
triggerall = movehit
triggerall = ctrl = 0
trigger1 = time >50
trigger1 = stateno = 1402


[state -1]
type = changestate
value = 90006
triggerall = command = "z"
triggerall = movehit
triggerall = ctrl = 0
trigger1 = time >63
trigger1 = stateno = 1401
trigger2 = time >63
trigger2 = stateno = 1400
trigger3 = time >22
trigger3 = stateno = 91008
trigger4 = time >33
trigger4 = stateno = 1401
trigger4 = anim = 1404


;************************
;**     Combo linkers  **
;************************
;(choperkick fuerte)
[state -1]
type = changestate
value = 1220
triggerall = movehit
triggerall = ctrl = 0
triggerall = time > 44
trigger1 = command = "TRFK"
trigger2 = command = "TRFK1"
trigger1 = stateno = 90000
trigger2 = stateno = 90000

;bola hacia tras con puño medio
[state -1]
type = changestate
value = 1110
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "FDB+Y"
trigger1 = time > 51
trigger1 = stateno = 90005
trigger2 = time > 39
trigger2 = stateno = 1300
trigger3 = time > 51
trigger3 = stateno = 90006
trigger4 = time > 44
trigger4 = stateno = 90000
trigger5 = time >22
trigger5 = stateno = 91008
trigger6 = time >42
trigger6 = stateno = 1300
trigger7 = time > 59
trigger7 = stateno = 90003



;bola hacia tras con puño debil
[state -1]
type = changestate
value = 1100
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "FDB+X"
trigger1 = time > 44
trigger1 = stateno = 90000
trigger2 = time >22
trigger2 = stateno = 91008
trigger3 = time > 51
trigger3 = stateno = 90006
trigger4 = time > 39
trigger4 = stateno = 1300
trigger5 = time > 51
trigger5 = stateno = 90005
trigger6 = time >42
trigger6 = stateno = 1300
trigger7 = time > 59
trigger7 = stateno = 90003




;bola hacia tras con puño debil despues de debil
[state -1]
type = changestate
value = 1110
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "FDB+X"
trigger1 = time > 16
trigger1 = stateno = 1100


;(OLASHOOO)
[state -1]
type = changestate
value = 1300
triggerall = movehit
triggerall = time >53
triggerall = Var(35) >6
triggerall = ctrl = 0
trigger1 = command = "hold_BACK,c"
trigger1 = stateno = 1220

;(turnkick)
[state -1]
type = changestate
value = 91008
triggerall = movehit
triggerall = ctrl = 0
triggerall = command = "hold_BACK,b"
trigger1 = time > 51
trigger1 = stateno = 90005
trigger2 = time > 51
trigger2 = stateno = 90006
trigger3 = time > 59
trigger3 = stateno = 90003
trigger4 = time > 44
trigger4 = stateno = 90000
trigger5 = var(35)>1
trigger5 = stateno = 90008

;hldback y puñofuerte
[state -1]
type = changestate
value = 247
triggerall = movehit
triggerall = ctrl = 0
trigger1 = Var(35) 
trigger1 = command = "hold_BACK,z"
trigger1 = time >20
trigger1 = stateno = 1110


;************************
;**     otros  **
;************************

[state -1]
type = changestate
value = 267
triggerall = movehit
triggerall = time >53
triggerall = Var(35) <7
triggerall = ctrl = 0
trigger1 = command = "hold_BACK,c"
trigger1 = stateno = 1220

;levantarse con OLASHOOOO
[state -1]
type = changestate
value = 1301
triggerall = time >1
triggerall = ctrl = 0
trigger1 = command = "TRFK"
trigger2 = command = "TRFK1"
trigger1 = anim = 5120 || anim = 5121 || anim = 5122
trigger2 = anim = 5120 || anim = 5121 || anim = 5122

;************************************
;----------- Finish Him ------------

[State -1]
type = Changestate
trigger1 = prevstateno != 55601
;trigger1 = ctrl 
trigger1 = P2Life <= 1 
trigger1 = NumHelper(9010) = 0
trigger1 = numhelper(55701)=0
trigger1 = P2StateNo != 003
trigger1 = RoundNo != 1
trigger1 = var(58) >= 1
;trigger1 = statetype = S
trigger1 = P2StateNo = 0
trigger1 = (p2statetype = S) || (p2statetype = C)
value = 9000 


;********************************************
;**  movimiento que hace la ai (comandos)  **
;********************************************
; COMBOBREAKER
[State -1,combobraker]
type = VarSet
trigger1 = 1
var(7) = ifelse (Random <= 3,1,ifelse(Random <= 2,2,0))

[State -1,combocreaker]
type = ChangeState
triggerall = life > 100
triggerall = Var(59)=2
triggerall = ctrl = 0
triggerall = movetype = H
triggerall = Var(32)>2
triggerall = statetype = S || statetype = C
trigger1 = var(7) = 1
value = 1230


[State -1,runcback]
type = ChangeState
triggerall = life > 100
triggerall = Var(59)=2
triggerall = ctrl = 0
triggerall = movetype = H
triggerall = Var(32)>2
triggerall = statetype = S || statetype = C
trigger1 = var(7) = 2
value = 105

; supermove decide
[State -1,supermove standing decide]
type = VarSet
trigger1 = 1
trigger1 = p2stateno != 21000
var(8) = ifelse (Random <= 100,4,ifelse (Random <= 200,2,ifelse (Random <= 300,3,ifelse (Random <= 400,1,ifelse (Random <= 500,0,ifelse (Random <= 750,6,ifelse (Random <= 800,7,5)))))))


    ;ELEK
	[State -1]
	type = ChangeState
	triggerall = stateno != 21000
      triggerall = stateno != 91011
      triggerall = stateno != 91000
      triggerall = stateno != 91002
      triggerall = stateno != 91004
      triggerall = stateno != 91006
        triggerall = stateno != 21009
        triggerall = var(8) =0 || var(8) = 4
triggerall = Var(59) = 2
triggerall = var(10)=0
triggerall = var(58)>=1
trigger1 = ctrl = 1 && statetype = S
trigger1 = p2stateno = 003
trigger1 = p2life <100 
	value = 22025

        ;HEAD
	[State -1]
	type = ChangeState
	triggerall = stateno != 21000
      triggerall = stateno != 91011
      triggerall = stateno != 91000
      triggerall = stateno != 91002
      triggerall = stateno != 91004
      triggerall = stateno != 91006
        triggerall = stateno != 21009
        trigger1 = p2name = "B.ORCHID BY AHRIMANES"
        trigger2 = p2name = "sub-zero by binho"
        trigger3 = p2name = "Kelly Blender(Elektra) by AHRIMANES"
        triggerall = var(8) = 1 || var(8) = 7
triggerall = Var(59) = 2
triggerall = var(10)=0
triggerall = var(58)>=1
triggerall = ctrl = 1 && statetype = S
triggerall = p2stateno = 003
triggerall = p2life <100 
	value = 22020

        ;BATS
	[State -1]
	type = ChangeState
	triggerall = stateno != 21000
      triggerall = stateno != 91011
      triggerall = stateno != 91000
      triggerall = stateno != 91002
      triggerall = stateno != 91004
      triggerall = stateno != 91006
        triggerall = stateno != 21009
        triggerall = var(8) = 2 ||  var(8) = 3
triggerall = Var(59) = 2
triggerall = var(10)=0
triggerall = var(58)>=1
trigger1 = ctrl = 1 && statetype = S
trigger1 = p2stateno = 003
trigger1 = p2life <100 
	value = 22013


;DANCE
[State -1]
type = ChangeState
trigger1 = P2name = "B.ORCHID BY AHRIMANES"
trigger2 = P2name = "cvssakura"
triggerall = stateno != 21000
triggerall = stateno != 91011
triggerall = stateno != 91000
triggerall = stateno != 91002
triggerall = stateno != 91004
triggerall = stateno != 91006
triggerall = stateno != 21009
triggerall = var(8) = 2 || var(8) = 4
triggerall = Var(59) = 2
triggerall = var(10)=0
triggerall = var(58)>=1
triggerall = ctrl = 1 && statetype = S
triggerall = p2stateno = 003
triggerall = p2life <100
value = 22001

;TITS
[State -1]
type = ChangeState
triggerall = stateno != 21000 ;enders
triggerall = stateno != 91011
triggerall = stateno != 91000
triggerall = stateno != 91002
triggerall = stateno != 91004
triggerall = stateno != 91006
triggerall = stateno != 21006
triggerall = stateno != 1403; openers
triggerall = stateno != 90000
triggerall = stateno != 90003
triggerall = stateno != 90005
triggerall = stateno != 90006
triggerall = Var(59) = 2
triggerall = Var(58) >= 1
triggerall = var(8) = 4
triggerall = var(10)=0
trigger1 = ctrl = 1
trigger1 = p2stateno = 003
trigger1 = p2life <100
trigger1 = statetype = S && P2bodydist X <= 70 && p2statetype = S
trigger2 = ctrl = 0
trigger2 = statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
trigger2 = p2life < 100
trigger2 = var(35) >1
value = 22010

;SAPO
[State -1]
type = ChangeState
triggerall = stateno != 21000 ;enders
triggerall = stateno != 91011
triggerall = stateno != 91000
triggerall = stateno != 91002
triggerall = stateno != 91004
triggerall = stateno != 91006
triggerall = stateno != 21006
triggerall = stateno != 1403; openers
triggerall = stateno != 90000
triggerall = stateno != 90003
triggerall = stateno != 90005
triggerall = stateno != 90006
triggerall = Var(59) = 2
triggerall = Var(58) >= 1
triggerall = var(8) = 6
triggerall = var(10)=0
trigger1 = ctrl = 1
trigger1 = p2stateno = 003
trigger1 = p2life <100
trigger1 = statetype = S && P2bodydist X <= 70 && p2statetype = S
trigger2 = ctrl = 0
trigger2 = statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
trigger2 = p2life < 100
trigger2 = var(35) >1
value = 21000

;ultra
;[State -1]
;type = ChangeState
;triggerall = stateno != 21006
;triggerall = stateno != 21000
;triggerall = Var(59) = 2
;triggerall = var(8) = 6
;triggerall = var(10)=0
;trigger1 = ctrl = 0
;trigger1 = statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
;trigger1 = p2life < 100
;trigger1 = var(35) >1
;value = 21006
;Ultra
	[State -1]
	type = ChangeState
triggerall = stateno != 21006;enders
	triggerall = stateno != 21000
triggerall = stateno != 91011
triggerall = stateno != 91000
triggerall = stateno != 91002
triggerall = stateno != 91004
triggerall = stateno != 91006
      triggerall = stateno != 21009
      triggerall = stateno != 1403; openers
triggerall = stateno != 90000
triggerall = stateno != 90003
triggerall = stateno != 90005
triggerall = stateno != 90006
	triggerall = Var(59) = 2
	triggerall = var(8) = 7
	triggerall = var(10)=0
	triggerall = ctrl = 0
	triggerall = statetype = S && p2movetype = H && P2bodydist X <= 70 && p2statetype = S
	triggerall = p2life < 100
	triggerall = var(35) >1
      ;triggerall = command = "TIGER-Y"
      ;triggerall = command != "FDB+Y"
      trigger1=1
	value = 21006



; CHOPER HARD KICK
[State -1]
type = ChangeState
value = 1220
triggerall = ctrl = 1
triggerall = Var(59)= 2
trigger1 = var(8) = 1
triggerall = statetype = S

;bola hacia tra con puño debil
[State -1]
type = ChangeState
value = 1100
triggerall = ctrl = 2
triggerall = Var(59)=2
trigger1 = var(8) = 5
triggerall = statetype = S

;bola hacia tra con puño medio
[State -1]
type = ChangeState
value = 1110
triggerall = ctrl = 1
triggerall = Var(59)=2
trigger1 = var(8) = 3
triggerall = statetype = S 

;TIGER-Y
[State -1]
type = ChangeState
value = 1401
triggerall = ctrl = 1
triggerall = Var(59)=2
trigger2 = enemy(0),numproj > 0
;trigger1 = numproj > 0 
trigger1 = var(8) = 4
triggerall = statetype = S 

;pindanger-x
[State -1]
type = ChangeState
value = 1000
triggerall = ctrl = 1
triggerall = Var(59)=2
trigger1 = var(8) = 2
triggerall = statetype = S 

;triggerall = p2bodydist X = [50,500]



;*****************************
;**   activacion de la AI   **
;*****************************

; AI Codes by O Ilusionista (took from MB-02's new version, mb-01 and Blaze Agent.
; I (O Ilusionista) and Ethan Lives has authorization to use many Soldats (and other peoples)
; codes, so dont start a flame war against him, ok?
; alterations by EX-INFERIS with Ilusionista permission!
;---------------------------------------------------------------------------
; A.I. - Start

[State -1, 1]
type = Helper
trigger1 = ctrl
trigger1 = (NumHelper(19000) = 0) && (Var(59) = 0)
helpertype	= Normal
name = "Quem sou eu "
id = 19000
pos = 0,0
postype = p1
facing = 0
stateno = 19000
keyctrl = 1
ownpal = 1
supermovetime = 0
pausemovetime = 0

[State -1, 2]
type = VarSet
trigger1 = (Var(59) = 1)
var(59) = 2

[State -1, 3]
type = VarSet
trigger1 = (Var(59) != 0) 
trigger1 = (RoundState != 2)
var(59) = 0

:[State -1, 4]
:type = ChangeState
:trigger1 = (RoundState = 3) 
:trigger1 = (StateType != A) && (Ctrl)
:value = 0

	
; Ativate A.I. -----------------------------------------------------------

[State -1]
type = VarSet
trigger1 = command = "cpu_1"
trigger2 = command = "cpu_2"
trigger3 = command = "cpu_3"
trigger4 = command = "cpu_4"
trigger5 = command = "cpu_5"
trigger6 = command = "cpu_6"
trigger7 = command = "cpu_7"
trigger8 = command = "cpu_8"
trigger9 = command = "cpu_9"
trigger10 = command = "cpu_10"
trigger11 = command = "cpu_11"
trigger12 = command = "cpu_12"
trigger13 = command = "cpu_13"
trigger14 = command = "cpu_14"
trigger15 = command = "cpu_15"
trigger16 = command = "cpu_16"
trigger17 = command = "cpu_17"
trigger18 = command = "cpu_18"
trigger19 = command = "cpu_19"
trigger20 = command = "cpu_20"
trigger21 = command = "cpu_21"
trigger22 = command = "cpu_22"
trigger23 = command = "cpu_23"
trigger24 = command = "cpu_24"
trigger25 = command = "cpu_25"
trigger26 = command = "cpu_26"
trigger27 = command = "cpu_27"
trigger28 = command = "cpu_28"
trigger29 = command = "cpu_29"
trigger30 = command = "cpu_30"
trigger31 = command = "cpu_31"
v = 59
value = 1
;---------------------------------------------------------------
;---------------------------------------------------------------

; Play "ouch" sound when hit light or medium
[State -1]
type = PlaySnd
triggerall = time = 1
triggerall = Alive
triggerall = stateno=5001
trigger1 = anim = 5000
trigger2 = anim = 5011
trigger3 = anim = 5005
trigger4 = anim = 5015
trigger5 = anim = 5020
trigger6 = anim = 5025
trigger7 = anim = 5027
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))


; Play "ouch" sound when hit light or medium
[State -1]
type = PlaySnd
triggerall = time = 1
triggerall = Alive
triggerall = stateno=5001
trigger1 = anim = 5001
trigger2 = anim = 5010
trigger3 = anim = 5006
trigger4 = anim = 5016
trigger5 = anim = 5021
trigger6 = anim = 5026
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))


; Play "ouch" sound when hit light or medium (in the air)
[State -1]
type = PlaySnd
triggerall = time = 1
triggerall = stateno=5001
triggerall = Alive
trigger1 = anim = 5020
trigger2 = anim = 5021
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))

;Play "ouch" sound when hit hard
[State -1]
type = PlaySnd
triggerall = time = 1
triggerall = stateno=5001||stateno=5030
triggerall = Alive
trigger1 = anim = 5002
trigger2 = anim = 5012
trigger3 = anim = 5022
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))

;Play "ouch" sound when hit hard (in the air)
[State -1]
type = PlaySnd
trigger1 = time = 1
triggerall = stateno=5001
trigger1 = Alive
trigger1 = anim = 5050
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))

;Play "ouch" when landing on back
[State -1]
type = PlaySnd
triggerall = MoveType = H
trigger1 = time = 1
triggerall = stateno=5001||stateno=5030
trigger1 = stateno = 5100
trigger2 = stateno = 5151
trigger1 = Alive
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))

;Play "ouch" when hit up
[State -1]
type = PlaySnd
triggerall = time = 1
trigger1 = anim = 5051
trigger1 = stateno = 5000
trigger2 = anim = 5030
trigger2 = stateno = 5020
triggerall = Alive
value = 2,11

;Play "ouch" when hit down
[State -1]
type = PlaySnd
triggerall = time = 1
trigger1 = stateno = 5100
trigger1 = anim = 5101
triggerall = Alive
value = 2,ifelse(random<50,2,ifelse(random<100,3,ifelse(random<150,4,ifelse(random<200,5,ifelse(random<250,6,ifelse(random<300,7,ifelse(random<350,8,ifelse(random<400,9,10))))))))

;====================================== StageID ==============================;
;===========================code for stage interaction =======================;


;; uses var(13) to count the fight time, this is needed since GameTime does
; not reset on each fight of arcade mode.
[State -1] 
type = VarAdd
trigger1 = 1
v = 13
value = 1


; identifies orchid stage, that has in StageID number of 55501
; if you want your character to react to other stages, add more triggers like this one, but change the ID number
; this trigger sets var(14) to stage ID number
[State -1] 
type = VarSet
triggerall = Var(13) = [1,3]
triggerall = var(14) = 0
trigger1 = ScreenPos Y = 55501 ; Vega Stage
;trigger2 = ScreenPos Y =   ; add your stage here
v = 14
value = floor(ScreenPos Y)


;edificio
;[State -1]
;type = explod
;triggerall = time > 5
;triggerall = numexplod(55501)=0
;trigger1 = var(14) =55501
;ID = 55501
;postype = p1
;anim = 55501
;ownpal = 1
;pos = 70,-5
;removetime = -1

;[State -1]
;type=ModifyExplod
;trigger1 = var(13)=200
;id = 55501
;accel = 0,-1

;buttons
;[State -1]
;type = explod
;trigger1 = command = "a"
;postype = back
;anim = 60014
;pos = 160,235
;removetime = 50
;facing = 1
;bindtime = -1

;edificio
[State -1]
type = helper
triggerall = time > 5
triggerall = numhelper(55501)=0
trigger1 = var(14) =55501
trigger1 = var(58) >= 1
sprpriority = 0
id = 55501
postype = p1
anim = 55501
stateno = 55500
helpertype = normal
name = "edificio"
ownpal = 1
pos = 70,-5


[State -1]
type = PlaySnd
trigger1 = NumHelper(9000) = 0 
trigger1 = p2stateno = 003
trigger1 = var(10)=0
trigger1 = animtime=1
value = 4,20

;edificio
;[State -1]
;type = posadd
;trigger1 = var(14) =55501
;y = -1


;=============================================================================;

